In [1]:
import pandas as pd

aluminum = pd.read_csv("NAMURLAKE_Aluminum.csv", encoding="latin1")
calcium = pd.read_csv("NAMURLAKE_Calcium.csv", encoding="latin1")
copper = pd.read_csv("NAMURLAKE_Copper.csv", encoding="latin1")
lead = pd.read_csv("NAMURLAKE_Lead.csv", encoding="latin1")
nickle = pd.read_csv("NAMURLAKE_Nickle.csv", encoding="latin1")
nitrogen = pd.read_csv("NAMURLAKE_Nitrogen.csv", encoding="latin1")
phosphorus = pd.read_csv("NAMURLAKE_Phosphorus.csv", encoding="latin1")
vanadium = pd.read_csv("NAMURLAKE_Vanadium.csv", encoding="latin1")

In [17]:
vanadium.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Sampling Timestamp  24 non-null     object
 1   Vanadium Dissolved  24 non-null     float64
 2   Site Name           24 non-null     object
 3   Station Name        24 non-null     object
 4   Depth               0 non-null      float64
 5   Value Sign          24 non-null     object
 6   Unit Symbol         24 non-null     object
 7   Method              24 non-null     int64
 8   Laboratory          24 non-null     object
 9   Sampling Number     24 non-null     object
 10  Sample Number       17 non-null     object
 11  RDL                 18 non-null     float64
 12  Sample Location     24 non-null     object
 13  Sample Type         17 non-null     object
 14  Sample Timestamp    24 non-null     object
dtypes: float64(3), int64(1), object(11)
memory usage: 2.9+ KB

In [4]:
aluminum.describe()

       Aluminum Dissolved  Depth       Method        RDL
count           24.000000    0.0    24.000000  18.000000
mean             1.009792    NaN  1890.166667   0.332828
std              0.817463    NaN   201.674655   0.398287
min              0.130000    NaN  1849.000000   0.000130
25%              0.450250    NaN  1849.000000   0.000130
50%              0.715000    NaN  1849.000000   0.130000
75%              1.350000    NaN  1849.000000   0.400000
max              3.680000    NaN  2837.000000   1.000000

In [6]:
aluminum.head(5)

,Sampling Timestamp,Aluminum Dissolved,Site Name,Station Name,Depth,Value Sign,Unit Symbol,Method,Laboratory,Sampling Number,Sample Number,RDL,Sample Location,Sample Type,Sample Timestamp
0,08/28/2003 8:55 AM,1.600,NAMUR LAKE,NAMUR LAKE,NaN,'---,µg/l,2837,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),03SWE01770,03SWE01770,NaN,Centre,SINGLE EUPHOTIC COMPOSITE,08/28/2003 7:55 AM
1,08/29/2004 8:45 AM,0.250,NAMUR LAKE,NAMUR LAKE,NaN,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),04SWE03018,04SWE02271,NaN,Centre,SINGLE EUPHOTIC COMPOSITE,08/29/2004 7:45 AM
2,08/27/2005 9:58 AM,0.570,NAMUR LAKE,NAMUR LAKE,NaN,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),05SWE02657,05SWE02658,NaN,Centre,SINGLE EUPHOTIC COMPOSITE,08/27/2005 8:58 AM
3,08/21/2007 9:40 AM,0.226,NAMUR LAKE,NAMUR LAKE,NaN,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),07SWE02684,07SWE02684,NaN,Centre,SINGLE EUPHOTIC COMPOSITE,08/21/2007 8:40 AM
4,08/27/2008 10:05 AM,0.467,NAMUR LAKE,NAMUR LAKE,NaN,'---,µg/l,1849,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),08SWE03930,08SWE02145,NaN,Centre,SINGLE EUPHOTIC COMPOSITE,08/27/2008 9:05 AM