In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("kearl_lake_cleaned (1).csv")

In [2]:
df

,lake,parameter,source_file,sampling_timestamp,sample_timestamp,measurement_value,measurement_value_raw,site_name,station_name,depth,value_sign,unit_symbol,method,laboratory,sampling_number,sample_number,rdl,sample_location,sample_type,vanadium_total_recoverable
0,kearl_lake,vanadium_total_recoverable,KEARL LAKE.csv,2003-03-24 12:00:00,2003-03-24 12:00:00,0.400,0.4,KEARL LAKE,KEARL LAKE,NaN,NaN,µg/l,1847,Alberta Research Council,104242,NaN,0.0002,NaN,NaN,0.4
1,kearl_lake,vanadium_total_recoverable,KEARL LAKE.csv,2004-07-26 12:00:00,2004-07-26 11:00:00,0.267,0.267,KEARL LAKE,KEARL LAKE,NaN,NaN,µg/l,1847,Alberta Research Council,104239,NaN,0.0002,NaN,NaN,0.267
2,kearl_lake,vanadium_total_recoverable,KEARL LAKE.csv,2004-08-24 15:05:00,2004-08-24 14:05:00,0.257,0.257,KEARL LAKE,KEARL LAKE,NaN,NaN,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),04SWE02174,04SWE02174,NaN,Centre,SINGLE EUPHOTIC COMPOSITE,0.257
3,kearl_lake,vanadium_total_recoverable,KEARL LAKE.csv,2005-07-22 12:00:00,2005-07-22 11:00:00,0.342,0.342,KEARL LAKE,KEARL LAKE,NaN,NaN,µg/l,1847,Alberta Research Council,104236,NaN,0.0002,NaN,NaN,0.342
4,kearl_lake,vanadium_total_recoverable,KEARL LAKE.csv,2005-08-30 08:55:00,2005-08-30 07:55:00,0.251,0.251,KEARL LAKE,KEARL LAKE,NaN,NaN,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),05SWE03024,05SWE03025,NaN,Centre,DISCRETE SAMPLE (GRAB),0.251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
657,kearl_lake,vanadium_total_recoverable,KEARL LAKE.csv,2015-08-29 07:30:00,2015-08-29 08:15:00,0.007,0.007,KEARL LAKE,KEARL LAKE,NaN,NaN,mg/l,3435,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,15SWE05523,15SWE05526,0.007,Centre,TRIP BLANK,0.007
658,kearl_lake,vanadium_total_recoverable,KEARL LAKE.csv,2015-08-29 07:30:00,2015-08-29 06:30:00,0.795,0.795,KEARL LAKE,KEARL LAKE,NaN,NaN,mg/l,3435,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,15SWE05523,15SWE05524,0.007,Centre,DISCRETE SAMPLE (GRAB),0.795
659,kearl_lake,vanadium_total_recoverable,KEARL LAKE.csv,2015-08-29 07:30:00,2015-08-29 08:00:00,0.009,0.009,KEARL LAKE,KEARL LAKE,NaN,NaN,mg/l,3435,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,15SWE05523,15SWE05525,0.007,Centre,FIELD BLANK,0.009
660,kearl_lake,vanadium_total_recoverable,KEARL LAKE.csv,2016-08-26 11:45:00,2016-08-26 10:45:00,0.881,0.881,KEARL LAKE,KEARL LAKE,NaN,NaN,mg/l,3435,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,16SWE08263,16SWE08264,0.006,Centre,SINGLE EUPHOTIC COMPOSITE,0.881
661,kearl_lake,vanadium_total_recoverable,KEARL LAKE.csv,2017-08-25 07:45:00,2017-08-25 06:45:00,0.854,0.854,KEARL LAKE,KEARL LAKE,NaN,NaN,mg/l,3435,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,17SWE12773,17SWE12774,0.006,Centre,DISCRETE SAMPLE (GRAB),0.854

In [14]:
rows_mg = df[df["unit_symbol"] == "mg/l"]

rows_mg

,lake,parameter,source_file,sampling_timestamp,sample_timestamp,measurement_value,measurement_value_raw,site_name,station_name,depth,value_sign,unit_symbol,method,laboratory,sampling_number,sample_number,rdl,sample_location,sample_type,vanadium_total_recoverable
93,kearl_lake,vanadium_total_recoverable,KEARL LAKE.csv,2000-09-27 12:00:00,2000-09-27 11:00:00,0.011,0.011,KEARL LAKE,KEARL LAKE,NaN,NaN,mg/l,3627,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,00SWE04029,00SWE04029,0.001,Centre,EUPHOTIC COMPOSITE,0.011
94,kearl_lake,vanadium_total_recoverable,KEARL LAKE.csv,2001-09-13 12:00:00,2001-09-13 11:00:00,0.013,0.013,KEARL LAKE,KEARL LAKE,NaN,NaN,mg/l,3627,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,01SWE03883,01SWE03883,0.001,Centre,VERTICAL INTEGRATED,0.013
95,kearl_lake,vanadium_total_recoverable,KEARL LAKE.csv,2002-09-04 12:00:00,2002-09-04 11:00:00,0.009,0.009,KEARL LAKE,KEARL LAKE,NaN,NaN,mg/l,3627,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,02SWE03131,02SWE03131,0.001,Centre,DISCRETE SAMPLE (GRAB),0.009
96,kearl_lake,vanadium_total_recoverable,KEARL LAKE.csv,2003-08-31 12:00:00,2003-08-31 11:00:00,0.023,0.023,KEARL LAKE,KEARL LAKE,NaN,NaN,mg/l,3627,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,03SWE02484,03SWE02484,0.001,Centre,DISCRETE SAMPLE (GRAB),0.023
97,kearl_lake,vanadium_total_recoverable,KEARL LAKE.csv,2004-06-17 14:30:00,2004-06-17 13:30:00,0.021,0.021,KEARL LAKE,KEARL LAKE,NaN,NaN,mg/l,3627,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,04SWE01029,04SWE01030,0.001,Centre,DISCRETE SAMPLE (GRAB),0.021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
657,kearl_lake,vanadium_total_recoverable,KEARL LAKE.csv,2015-08-29 07:30:00,2015-08-29 08:15:00,0.007,0.007,KEARL LAKE,KEARL LAKE,NaN,NaN,mg/l,3435,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,15SWE05523,15SWE05526,0.007,Centre,TRIP BLANK,0.007
658,kearl_lake,vanadium_total_recoverable,KEARL LAKE.csv,2015-08-29 07:30:00,2015-08-29 06:30:00,0.795,0.795,KEARL LAKE,KEARL LAKE,NaN,NaN,mg/l,3435,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,15SWE05523,15SWE05524,0.007,Centre,DISCRETE SAMPLE (GRAB),0.795
659,kearl_lake,vanadium_total_recoverable,KEARL LAKE.csv,2015-08-29 07:30:00,2015-08-29 08:00:00,0.009,0.009,KEARL LAKE,KEARL LAKE,NaN,NaN,mg/l,3435,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,15SWE05523,15SWE05525,0.007,Centre,FIELD BLANK,0.009
660,kearl_lake,vanadium_total_recoverable,KEARL LAKE.csv,2016-08-26 11:45:00,2016-08-26 10:45:00,0.881,0.881,KEARL LAKE,KEARL LAKE,NaN,NaN,mg/l,3435,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,16SWE08263,16SWE08264,0.006,Centre,SINGLE EUPHOTIC COMPOSITE,0.881
661,kearl_lake,vanadium_total_recoverable,KEARL LAKE.csv,2017-08-25 07:45:00,2017-08-25 06:45:00,0.854,0.854,KEARL LAKE,KEARL LAKE,NaN,NaN,mg/l,3435,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,17SWE12773,17SWE12774,0.006,Centre,DISCRETE SAMPLE (GRAB),0.854

In [17]:
dfunits = df.copy()

dfunits["vanadium_total_recoverable"] = pd.to_numeric(
    dfunits["vanadium_total_recoverable"], errors="coerce"
)

condition = dfunits['unit_symbol'] == 'mg/l'
dfunits.loc[condition, 'vanadium_total_recoverable'] *= 1000
dfunits.loc[condition, 'unit_symbol'] = 'µg/l'

dfunits

,lake,parameter,source_file,sampling_timestamp,sample_timestamp,measurement_value,measurement_value_raw,site_name,station_name,depth,value_sign,unit_symbol,method,laboratory,sampling_number,sample_number,rdl,sample_location,sample_type,vanadium_total_recoverable
0,kearl_lake,vanadium_total_recoverable,KEARL LAKE.csv,2003-03-24 12:00:00,2003-03-24 12:00:00,0.400,0.4,KEARL LAKE,KEARL LAKE,NaN,NaN,µg/l,1847,Alberta Research Council,104242,NaN,0.0002,NaN,NaN,0.400
1,kearl_lake,vanadium_total_recoverable,KEARL LAKE.csv,2004-07-26 12:00:00,2004-07-26 11:00:00,0.267,0.267,KEARL LAKE,KEARL LAKE,NaN,NaN,µg/l,1847,Alberta Research Council,104239,NaN,0.0002,NaN,NaN,0.267
2,kearl_lake,vanadium_total_recoverable,KEARL LAKE.csv,2004-08-24 15:05:00,2004-08-24 14:05:00,0.257,0.257,KEARL LAKE,KEARL LAKE,NaN,NaN,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),04SWE02174,04SWE02174,NaN,Centre,SINGLE EUPHOTIC COMPOSITE,0.257
3,kearl_lake,vanadium_total_recoverable,KEARL LAKE.csv,2005-07-22 12:00:00,2005-07-22 11:00:00,0.342,0.342,KEARL LAKE,KEARL LAKE,NaN,NaN,µg/l,1847,Alberta Research Council,104236,NaN,0.0002,NaN,NaN,0.342
4,kearl_lake,vanadium_total_recoverable,KEARL LAKE.csv,2005-08-30 08:55:00,2005-08-30 07:55:00,0.251,0.251,KEARL LAKE,KEARL LAKE,NaN,NaN,µg/l,1847,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),05SWE03024,05SWE03025,NaN,Centre,DISCRETE SAMPLE (GRAB),0.251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
657,kearl_lake,vanadium_total_recoverable,KEARL LAKE.csv,2015-08-29 07:30:00,2015-08-29 08:15:00,0.007,0.007,KEARL LAKE,KEARL LAKE,NaN,NaN,µg/l,3435,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,15SWE05523,15SWE05526,0.007,Centre,TRIP BLANK,7.000
658,kearl_lake,vanadium_total_recoverable,KEARL LAKE.csv,2015-08-29 07:30:00,2015-08-29 06:30:00,0.795,0.795,KEARL LAKE,KEARL LAKE,NaN,NaN,µg/l,3435,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,15SWE05523,15SWE05524,0.007,Centre,DISCRETE SAMPLE (GRAB),795.000
659,kearl_lake,vanadium_total_recoverable,KEARL LAKE.csv,2015-08-29 07:30:00,2015-08-29 08:00:00,0.009,0.009,KEARL LAKE,KEARL LAKE,NaN,NaN,µg/l,3435,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,15SWE05523,15SWE05525,0.007,Centre,FIELD BLANK,9.000
660,kearl_lake,vanadium_total_recoverable,KEARL LAKE.csv,2016-08-26 11:45:00,2016-08-26 10:45:00,0.881,0.881,KEARL LAKE,KEARL LAKE,NaN,NaN,µg/l,3435,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,16SWE08263,16SWE08264,0.006,Centre,SINGLE EUPHOTIC COMPOSITE,881.000
661,kearl_lake,vanadium_total_recoverable,KEARL LAKE.csv,2017-08-25 07:45:00,2017-08-25 06:45:00,0.854,0.854,KEARL LAKE,KEARL LAKE,NaN,NaN,µg/l,3435,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,17SWE12773,17SWE12774,0.006,Centre,DISCRETE SAMPLE (GRAB),854.000

In [18]:
rows_mg = dfunits[dfunits["unit_symbol"] == "mg/l"]

rows_mg

Empty DataFrame
Columns: [lake, parameter, source_file, sampling_timestamp, sample_timestamp, measurement_value, measurement_value_raw, site_name, station_name, depth, value_sign, unit_symbol, method, laboratory, sampling_number, sample_number, rdl, sample_location, sample_type, vanadium_total_recoverable]
Index: []

In [25]:
df_clean = dfunits.drop(columns=[
    "parameter",
    "source_file",
    "sample_timestamp",
    "measurement_value_raw",
    "station_name",
    "method",
    "sampling_number",
    "sample_number",
    "sample_location",
    "sample_type"

])
df_clean

,lake,sampling_timestamp,measurement_value,site_name,depth,value_sign,unit_symbol,laboratory,rdl,vanadium_total_recoverable
0,kearl_lake,2003-03-24 12:00:00,0.400,KEARL LAKE,NaN,NaN,µg/l,Alberta Research Council,0.0002,0.400
1,kearl_lake,2004-07-26 12:00:00,0.267,KEARL LAKE,NaN,NaN,µg/l,Alberta Research Council,0.0002,0.267
2,kearl_lake,2004-08-24 15:05:00,0.257,KEARL LAKE,NaN,NaN,µg/l,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,0.257
3,kearl_lake,2005-07-22 12:00:00,0.342,KEARL LAKE,NaN,NaN,µg/l,Alberta Research Council,0.0002,0.342
4,kearl_lake,2005-08-30 08:55:00,0.251,KEARL LAKE,NaN,NaN,µg/l,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,0.251
...,...,...,...,...,...,...,...,...,...,...
657,kearl_lake,2015-08-29 07:30:00,0.007,KEARL LAKE,NaN,NaN,µg/l,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.007,7.000
658,kearl_lake,2015-08-29 07:30:00,0.795,KEARL LAKE,NaN,NaN,µg/l,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.007,795.000
659,kearl_lake,2015-08-29 07:30:00,0.009,KEARL LAKE,NaN,NaN,µg/l,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.007,9.000
660,kearl_lake,2016-08-26 11:45:00,0.881,KEARL LAKE,NaN,NaN,µg/l,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.006,881.000
661,kearl_lake,2017-08-25 07:45:00,0.854,KEARL LAKE,NaN,NaN,µg/l,UNIVERSITY OF ALBERTA - BIOGEOCHEMICAL ANALYTI...,0.006,854.000

In [26]:
header_indices = df_clean[df_clean['site_name'] == 'Site Name'].index.tolist()
print(header_indices)
print(len(header_indices))

[33, 65, 92, 139, 186, 233, 249, 263, 297, 329, 366, 440, 474, 506, 538, 572, 604, 638]
18

In [27]:
starts = [33, 65, 92, 139, 186, 233, 249, 263, 297, 329, 366, 440, 474, 506, 538, 572, 604, 638]

dfs = []

for i in range(len(starts)):
    
    start = starts[i]
    
    if i < len(starts) - 1:
        end = starts[i+1]
        df_split = df_clean.iloc[start:end]
    else:
        df_split = df_clean.iloc[start:]   # last section
    
    dfs.append(df_split)

In [28]:
#clean_dfs = []

for d in dfs:
    
    chem_name = d.iloc[0, -1]   # chemical name from header row
    
    d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
    
    d.drop(index=d.index[0], inplace=True)  # remove header row

C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.rename(columns={d.columns[-1]: chem_name}, inplace=True)
C:\Users\morsal.n\AppData\Local\Temp\ipykernel_35904\1715359265.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.drop(index=d.index[0], inplace=True)  # remove header row

In [30]:
"""for i, d in enumerate(clean_dfs):
    print(f"\nDataFrame {i}")
    print(d)"""
dfs[9].head()

,lake,sampling_timestamp,measurement_value,site_name,depth,value_sign,unit_symbol,laboratory,rdl,Calcium Total
330,kearl_lake,2003-03-24 12:00:00,38.6,KEARL LAKE,NaN,NaN,µg/l,Alberta Research Council,0.1,38600.0
331,kearl_lake,2004-07-26 12:00:00,17.6,KEARL LAKE,NaN,NaN,µg/l,Alberta Research Council,0.1,17600.0
332,kearl_lake,2004-08-24 15:05:00,18.1,KEARL LAKE,NaN,NaN,µg/l,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,18100.0
333,kearl_lake,2005-07-22 12:00:00,15.4,KEARL LAKE,NaN,NaN,µg/l,Alberta Research Council,0.1,15400.0
334,kearl_lake,2005-08-30 08:55:00,15.2,KEARL LAKE,NaN,NaN,µg/l,AITF-EAS (ENVIRONMENTAL ANALYTICAL SERVICES),NaN,15200.0

In [29]:

# Aluminum
dfs[12] = dfs[12].rename(columns={dfs[12].columns[-1]: "Aluminum Dissolved"})
aluminum_df = dfs[12][["sampling_timestamp", "Aluminum Dissolved"]]

dfs[11] = dfs[11].rename(columns={dfs[11].columns[-1]: "Aluminum Total Recoverable"})
aluminum_total_df = dfs[11][["sampling_timestamp", "Aluminum Total Recoverable"]]

# Calcium
dfs[10] = dfs[10].rename(columns={dfs[10].columns[-1]: "Calcium Dissolved"})
calcium_df = dfs[10][["sampling_timestamp", "Calcium Dissolved"]]

dfs[9] = dfs[9].rename(columns={dfs[9].columns[-1]: "Calcium Total"})
calcium_total_df = dfs[9][["sampling_timestamp", "Calcium Total"]]

# Copper
dfs[8] = dfs[8].rename(columns={dfs[8].columns[-1]: "Copper Dissolved"})
copper_df = dfs[8][["sampling_timestamp", "Copper Dissolved"]]

dfs[7] = dfs[7].rename(columns={dfs[7].columns[-1]: "Copper Total Recoverable"})
copper_total_df = dfs[7][["sampling_timestamp", "Copper Total Recoverable"]]

# Lead
dfs[13] = dfs[13].rename(columns={dfs[13].columns[-1]: "Lead Dissolved"})
lead_df = dfs[13][["sampling_timestamp", "Lead Dissolved"]]

dfs[14] = dfs[14].rename(columns={dfs[14].columns[-1]: "Lead Total Recoverable"})
lead_total_df = dfs[14][["sampling_timestamp", "Lead Total Recoverable"]]

# Nickel
dfs[15] = dfs[15].rename(columns={dfs[15].columns[-1]: "Nickel Dissolved"})
nickel_df = dfs[15][["sampling_timestamp", "Nickel Dissolved"]]

dfs[16] = dfs[16].rename(columns={dfs[16].columns[-1]: "Nickel Total Recoverable"})
nickel_total_df = dfs[16][["sampling_timestamp", "Nickel Total Recoverable"]]

# Nitrogen
dfs[17] = dfs[17].rename(columns={dfs[17].columns[-1]: "Nitrogen Dissolved"})
nitrogen_df = dfs[17][["sampling_timestamp", "Nitrogen Dissolved"]]

# Phosphorus
dfs[3] = dfs[3].rename(columns={dfs[3].columns[-1]: "Phosphorus Total Dissolved"})
phosphorus_df = dfs[3][["sampling_timestamp", "Phosphorus Total Dissolved"]]

dfs[2] = dfs[2].rename(columns={dfs[2].columns[-1]: "Phosphorus Total"})
phosphorus_total_df = dfs[2][["sampling_timestamp", "Phosphorus Total"]]

# Vanadium
dfs[0] = dfs[0].rename(columns={dfs[0].columns[-1]: "Vanadium Dissolved"})
vanadium_df = dfs[0][["sampling_timestamp", "Vanadium Dissolved"]]

# Turbidity
dfs[1] = dfs[1].rename(columns={dfs[1].columns[-1]: "Turbidity"})
turbidity_df = dfs[1][["sampling_timestamp", "Turbidity"]]

# pH
dfs[4] = dfs[4].rename(columns={dfs[4].columns[-1]: "pH"})
ph_df = dfs[4][["sampling_timestamp", "pH"]]

# Oxygen BOD
dfs[6] = dfs[6].rename(columns={dfs[6].columns[-1]: "OXYGEN BIOCHEMICAL DEMAND"})
oxygen_bod_df = dfs[6][["sampling_timestamp", "OXYGEN BIOCHEMICAL DEMAND"]]

dfs[5] = dfs[5].rename(columns={dfs[5].columns[-1]: "Oxygen dissolved % saturation"})
oxygen_sat_df = dfs[5][["sampling_timestamp", "Oxygen dissolved % saturation"]]

In [31]:
kearl_clean = pd.concat(
    [
         aluminum_df,
        aluminum_total_df,
        calcium_df,
        calcium_total_df,
        copper_df,
        copper_total_df,
        lead_df,
        lead_total_df,
        nickel_df,
        nickel_total_df,
        nitrogen_df,
        phosphorus_df,
        phosphorus_total_df,
        vanadium_df,
        turbidity_df,
        ph_df,
        oxygen_sat_df,
        oxygen_bod_df
    ],
    axis=0
)


kearl_clean["Site Name"] = "Kearl LAKE"
kearl_clean["Unit Symbol"] = "µg/l"

kearl_clean= kearl_clean.groupby("sampling_timestamp", as_index=False).first()

kearl_clean["sampling_timestamp"] = pd.to_datetime(
    kearl_clean["sampling_timestamp"], errors="coerce"
)

In [32]:
kearl_clean = kearl_clean.sort_values(by="sampling_timestamp")
kearl_clean

,sampling_timestamp,Aluminum Dissolved,Aluminum Total Recoverable,Calcium Dissolved,Calcium Total,Copper Dissolved,Copper Total Recoverable,Lead Dissolved,Lead Total Recoverable,Nickel Dissolved,...,Nitrogen Dissolved,Phosphorus Total Dissolved,Phosphorus Total,Vanadium Dissolved,Turbidity,pH,Oxygen dissolved % saturation,OXYGEN BIOCHEMICAL DEMAND,Site Name,Unit Symbol
0,2000-09-27 12:00:00,NaN,NaN,20300.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,9.0,11.0,NaN,NaN,8.00,NaN,NaN,Kearl LAKE,µg/l
1,2001-09-13 12:00:00,NaN,NaN,19600.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,13.0,13.0,NaN,NaN,7.90,NaN,NaN,Kearl LAKE,µg/l
2,2002-09-04 12:00:00,NaN,NaN,20600.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2.0,9.0,NaN,NaN,7.70,NaN,NaN,Kearl LAKE,µg/l
3,2003-03-24 12:00:00,6.000,19.40,37800.0,38600.0,5.400,7.700,1.20000,1.7000,0.5000,...,NaN,8.0,15.0,0.400,NaN,7.80,1.8,2000.0,Kearl LAKE,µg/l
4,2003-08-31 12:00:00,NaN,NaN,16900.0,NaN,NaN,NaN,NaN,NaN,NaN,...,1127.0,6.0,23.0,NaN,8.30,7.94,NaN,NaN,Kearl LAKE,µg/l
5,2004-06-17 14:30:00,NaN,NaN,15100.0,NaN,NaN,NaN,NaN,NaN,NaN,...,773.0,3.0,21.0,NaN,NaN,7.94,NaN,NaN,Kearl LAKE,µg/l
6,2004-07-14 09:15:00,NaN,NaN,16100.0,NaN,NaN,NaN,NaN,NaN,NaN,...,880.0,9.0,25.0,NaN,1.50,7.97,NaN,NaN,Kearl LAKE,µg/l
7,2004-07-26 12:00:00,2.120,17.80,17400.0,17600.0,0.170,0.223,0.00726,0.1430,0.1780,...,NaN,14.0,19.0,0.200,NaN,8.10,NaN,2000.0,Kearl LAKE,µg/l
8,2004-08-24 15:05:00,0.940,12.70,16600.0,18100.0,0.118,0.166,0.00590,0.0314,0.0200,...,942.0,7.0,27.0,0.201,1.50,8.04,NaN,NaN,Kearl LAKE,µg/l
9,2004-09-25 13:10:00,NaN,NaN,17200.0,NaN,NaN,NaN,NaN,NaN,NaN,...,1137.0,7.0,28.0,NaN,NaN,7.98,NaN,NaN,Kearl LAKE,µg/l
10,2005-04-07 08:00:00,NaN,NaN,21600.0,NaN,NaN,NaN,NaN,NaN,NaN,...,1881.0,7.0,17.0,NaN,1.45,7.49,NaN,NaN,Kearl LAKE,µg/l
11,2005-05-26 12:00:00,NaN,NaN,12400.0,NaN,NaN,NaN,NaN,NaN,NaN,...,955.0,7.0,20.0,NaN,NaN,7.82,NaN,NaN,Kearl LAKE,µg/l
12,2005-07-13 12:00:00,NaN,NaN,18600.0,NaN,NaN,NaN,NaN,NaN,NaN,...,1062.0,9.0,23.0,NaN,NaN,7.69,NaN,NaN,Kearl LAKE,µg/l
13,2005-07-22 12:00:00,2.690,23.20,15100.0,15400.0,0.100,0.100,0.03120,0.0370,0.0600,...,NaN,5.0,16.0,0.257,NaN,7.90,91.0,2000.0,Kearl LAKE,µg/l
14,2005-08-30 08:55:00,NaN,14.00,27570.0,15200.0,NaN,0.200,NaN,0.0485,NaN,...,943.0,5.0,22.0,NaN,1.50,8.00,NaN,NaN,Kearl LAKE,µg/l
15,2005-09-28 12:00:00,NaN,NaN,30010.0,NaN,NaN,NaN,NaN,NaN,NaN,...,956.0,6.0,25.0,NaN,NaN,7.98,NaN,NaN,Kearl LAKE,µg/l
16,2006-08-23 12:00:00,NaN,20.80,16380.0,16700.0,NaN,0.488,NaN,0.0550,NaN,...,1190.0,7.0,34.0,NaN,NaN,7.98,NaN,NaN,Kearl LAKE,µg/l
17,2006-09-14 12:00:00,1.430,56.80,17800.0,18800.0,0.234,0.285,0.00600,0.0761,0.0600,...,NaN,8.0,46.0,0.311,NaN,8.00,NaN,3000.0,Kearl LAKE,µg/l
18,2007-08-23 09:45:00,0.514,16.60,16570.0,18400.0,0.130,0.141,0.00120,0.0801,0.0158,...,1160.0,39.0,39.0,0.325,3.40,7.88,NaN,NaN,Kearl LAKE,µg/l
19,2007-09-11 12:00:00,1.000,23.00,17400.0,18500.0,0.160,0.162,0.02000,0.0895,0.0730,...,NaN,6.0,41.0,0.298,NaN,8.10,NaN,2000.0,Kearl LAKE,µg/l
20,2008-09-05 12:15:00,1.310,6.72,20100.0,18900.0,0.240,0.665,0.00250,0.0722,0.0050,...,1020.0,9.0,21.0,0.352,1.49,8.32,NaN,NaN,Kearl LAKE,µg/l
21,2009-03-17 09:25:00,0.858,9.73,27100.0,28400.0,0.316,0.319,0.18600,0.5810,0.0470,...,NaN,12.0,16.0,0.175,0.85,6.89,NaN,600.0,Kearl LAKE,µg/l
22,2009-08-17 16:15:00,1.180,11.90,19100.0,19300.0,0.174,0.176,0.00600,0.0291,0.1510,...,856.0,4.0,19.0,0.161,2.24,8.17,NaN,NaN,Kearl LAKE,µg/l
23,2009-09-18 12:00:00,1.000,13.60,21300.0,22000.0,0.410,0.415,0.00680,0.0137,0.1670,...,NaN,6.2,19.6,0.164,NaN,8.18,NaN,2200.0,Kearl LAKE,µg/l
24,2010-08-31 15:45:00,1.030,14.20,21200.0,17500.0,0.127,0.128,0.00530,0.0409,0.0120,...,NaN,6.0,30.0,0.246,NaN,8.32,NaN,NaN,Kearl LAKE,µg/l
25,2011-09-01 08:30:00,2.110,16.60,21420.0,18700.0,0.166,0.168,0.03500,0.0354,0.0633,...,924.0,5.0,30.0,0.175,2.75,8.03,NaN,NaN,Kearl LAKE,µg/l
26,2011-09-10 12:00:00,1.300,11.40,17900.0,19600.0,0.362,0.366,0.10000,0.1000,0.1000,...,NaN,3.9,21.8,0.209,NaN,8.26,NaN,2200.0,Kearl LAKE,µg/l
27,2012-08-26 15:45:00,1.060,9.96,22680.0,20400.0,0.342,0.346,0.00210,0.0123,0.0050,...,1040.0,4.0,23.0,0.170,1.95,8.15,NaN,NaN,Kearl LAKE,µg/l
28,2012-09-08 12:00:00,1.000,10.10,19800.0,20500.0,0.100,0.100,0.10000,0.1000,0.1000,...,NaN,7.4,20.2,0.168,NaN,8.06,NaN,2000.0,Kearl LAKE,µg/l
29,2013-08-28 13:10:00,2.670,5.85,19820.0,19100.0,0.131,0.132,0.01740,0.0198,0.1240,...,1028.0,6.0,18.0,0.194,1.42,8.02,NaN,NaN,Kearl LAKE,µg/l
30,2013-09-07 12:00:00,4.720,10.00,18900.0,19400.0,0.113,0.163,0.10000,0.1000,0.2440,...,NaN,7.9,31.5,0.171,NaN,8.07,NaN,2000.0,Kearl LAKE,µg/l
31,2014-08-18 16:00:00,1.070,20.80,17300.0,19000.0,0.080,0.050,0.00400,0.0080,0.0060,...,864.0,6.0,16.0,0.120,2.31,8.13,NaN,NaN,Kearl LAKE,µg/l
32,2014-09-11 12:00:00,1.040,7.30,18500.0,20100.0,0.360,0.370,0.01300,0.0140,0.0230,...,NaN,1.6,11.5,0.110,NaN,8.13,NaN,2000.0,Kearl LAKE,µg/l
33,2015-08-29 07:30:00,1.600,25.70,20200.0,21100.0,0.100,0.100,0.03000,0.0300,0.0060,...,7.0,2.0,1.0,0.180,0.05,5.70,NaN,NaN,Kearl LAKE,µg/l
34,2016-03-15 12:00:00,1.170,26.10,33100.0,33100.0,0.190,0.200,0.03200,0.0320,0.3620,...,NaN,3.0,35.0,0.090,2.80,7.51,NaN,8300.0,Kearl LAKE,µg/l
35,2016-07-19 12:00:00,2.440,17.00,15200.0,15300.0,0.210,0.210,0.01200,0.0430,0.1960,...,NaN,14.0,38.0,0.290,5.30,8.61,NaN,NaN,Kearl LAKE,µg/l
36,2016-08-26 11:45:00,2.160,10.40,24600.0,24700.0,0.230,0.280,0.03500,0.4840,0.0060,...,881.0,5.0,27.0,0.210,3.77,8.55,NaN,NaN,Kearl LAKE,µg/l
37,2016-09-20 12:00:00,1.400,19.40,23200.0,23600.0,0.180,0.190,0.02400,0.0250,0.0060,...,NaN,5.0,17.0,0.090,2.40,8.03,NaN,NaN,Kearl LAKE,µg/l
38,2017-03-13 12:00:00,1.190,18.40,43000.0,43600.0,0.180,0.310,0.00400,0.0580,0.1700,...,NaN,3.0,28.0,0.060,1.60,7.64,NaN,NaN,Kearl LAKE,µg/l
39,2017-08-25 07:45:00,1.300,8.00,24400.0,24300.0,0.120,0.190,0.02000,0.0210,0.1200,...,854.0,6.0,21.0,0.108,1.03,8.21,NaN,NaN,Kearl LAKE,µg/l
40,2020-09-18 10:40:00,1.000,3.70,17900.0,18400.0,0.080,0.080,0.02000,0.0050,0.2300,...,NaN,4.2,7.7,0.072,0.84,7.60,99.7,NaN,Kearl LAKE,µg/l
41,2021-08-18 15:15:00,2.000,10.90,23000.0,NaN,0.130,0.200,0.02000,0.0620,0.2700,...,NaN,4.1,25.0,0.340,2.80,7.25,110.8,NaN,Kearl LAKE,µg/l
42,2022-09-16 07:20:00,16.000,27.20,22000.0,NaN,0.130,0.150,0.02000,0.0410,0.3300,...,NaN,7.9,34.0,0.298,2.30,6.99,76.1,NaN,Kearl LAKE,µg/l

In [12]:
kearl_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   sampling_timestamp             43 non-null     datetime64[ns]
 1   Aluminum Dissolved             30 non-null     object
 2   Aluminum Total Recoverable     32 non-null     object
 3   Calcium Dissolved              43 non-null     object
 4   Calcium Total                  30 non-null     object
 5   Copper Dissolved               30 non-null     object
 6   Copper Total Recoverable       32 non-null     object
 7   Lead Dissolved                 30 non-null     object
 8   Lead Total Recoverable         32 non-null     object
 9   Nickel Dissolved               30 non-null     object
 10  Nickel Total Recoverable       32 non-null     object
 11  Nitrogen Dissolved             21 non-null     object
 12  Phosphorus Total Dissolved     43 non-null     object
 13  Phosphorus Total               43 non-null     object
 14  Vanadium Dissolved             30 non-null     object
 15  Turbidity                      23 non-null     object
 16  pH                             43 non-null     object
 17  Oxygen dissolved % saturation  5 non-null      object
 18  OXYGEN BIOCHEMICAL DEMAND      12 non-null     object
 19  Site Name                      43 non-null     object
 20  Unit Symbol                    43 non-null     object
dtypes: datetime64[ns](1), object(20)
memory usage: 7.2+ KB

In [33]:
kearl_clean.to_csv("KearlLake_Data.csv", index= False)